# Generated by Django 2.1.7 on 2019-04-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('university_id', models.IntegerField()),
                ('points', models.IntegerField()),
                ('photo_url', models.CharField(max_length=200)),
            ],
        ),
    ]
