# Generated by Django 2.2 on 2019-05-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20190518_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo_url',
            field=models.CharField(max_length=200),
        ),
    ]
