# Generated by Django 2.2 on 2019-05-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20190518_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo_url',
            field=models.CharField(max_length=255),
        ),
    ]
