# Generated by Django 2.2.2 on 2019-06-03 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_auto_20190521_1544'),
        ('players', '0004_auto_20190521_1038'),
    ]

    operations = [
    ]
