# Generated by Django 2.2.2 on 2019-06-16 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_merge_20190603_2152'),
        ('players', '0006_auto_20190518_1830'),
    ]

    operations = [
    ]
