# Generated by Django 2.2.2 on 2019-06-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_merge_20190616_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='university_id',
            field=models.CharField(max_length=255),
        ),
    ]
