# Generated by Django 2.1.7 on 2019-04-13 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_auto_20190413_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='url_image',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
