# Generated by Django 2.1.7 on 2019-04-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_evento_url_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='reward_id',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
