# Generated by Django 2.2 on 2019-04-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_evento_reward_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='reward_id',
            field=models.IntegerField(max_length=255),
        ),
    ]
