# Generated by Django 2.2 on 2019-04-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_auto_20190430_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='reward_id',
            field=models.IntegerField(),
        ),
    ]
