# Generated by Django 2.2.2 on 2019-06-08 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_auto_20190430_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
