# Generated by Django 2.2.1 on 2019-05-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_auto_20190430_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento_Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_id', models.IntegerField()),
                ('player_id', models.IntegerField()),
            ],
        ),
    ]
