# Generated by Django 2.2.2 on 2019-06-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_auto_20190608_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='time',
        ),
        migrations.AlterField(
            model_name='evento',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
