# Generated by Django 2.2.2 on 2019-06-14 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_auto_20190608_1955'),
        ('eventos', '0013_evento_creator_id'),
    ]

    operations = [
    ]
